import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Undoes the dev-artifact rewrite the PAYWALL_MODE=trial server leaves behind.
 *
 * `next dev` regenerates tsconfig.json's `include` globs on boot to wire in
 * `${distDir}/...`. The trial server on :3101 runs with
 * NEXT_DIST_DIR=".next/e2e-trial" (see playwright.config.ts / next.config.ts),
 * so after a run that booted it the TRACKED tsconfig.json carries a
 * ".next/e2e-trial" segment and the working tree is left dirty. On a test-only
 * CI leg no default-distDir `next dev` ever runs afterward to heal it, so a
 * clean-tree gate would fail, or the e2e-trial globs could be committed by
 * accident. (next-env.d.ts also gets rewritten, but it is gitignored and
 * regenerated by `next typegen` in the typecheck script, so it needs no heal.)
 *
 * The restore is SURGICAL — no `git checkout`, so it needs no git (works in
 * bare checkouts) and preserves any unrelated local edits: `next dev` ADDS its
 * distDir's type-include globs to the `include` array without removing the
 * other distDir's, so a blind string substitution would leave duplicates. We
 * drop exactly the `include` entries that contain the marker, which leaves the
 * committed set intact. JSON round-trip keeps commas/formatting valid.
 *
 * The restore is gated on the marker actually being present, so an unrelated
 * run (or one where the default server wrote last) is a no-op.
 *
 * INVARIANT: `next typegen` / `next dev` leave the tracked tsconfig.json alone
 * ONLY because both default-distDir globs (".next/types/**\/*.ts" and
 * ".next/dev/types/**\/*.ts") are already committed in `include` — Next adds
 * missing entries on boot. Removing either from tsconfig.json makes every
 * typecheck/dev run dirty the tree again.
 */

const MARKER = ".next/e2e-trial";

function restoreTsconfig(path: string): void {
  const before = readFileSync(path, "utf8");
  if (!before.includes(MARKER)) return;
  const cfg = JSON.parse(before) as { include?: unknown };
  if (Array.isArray(cfg.include)) {
    cfg.include = cfg.include.filter(
      (glob) => !(typeof glob === "string" && glob.includes(MARKER))
    );
  }
  const after = `${JSON.stringify(cfg, null, 2)}\n`;
  if (after !== before) writeFileSync(path, after);
}

export default function globalTeardown(): void {
  const tsconfig = join(process.cwd(), "tsconfig.json");
  if (existsSync(tsconfig)) restoreTsconfig(tsconfig);
}
